spring.application.name=JobPortalWeb

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/jobportal
spring.datasource.username=postgres
spring.datasource.password=Neha@74191
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# 15 min in ms
jwt.access-token-expiry=900000
# 7 days in ms
jwt.refresh-token-expiry=604800000